### ISSUE TITLE
Exception when currency is None

### ISSUE THREAD

**Issue by jonathansaetre** [bradbase/python-harvest_apiv2#12]
Hey, I'm getting this exception, probably because currency is not assigned value.
But I'm not administrator, so I'm not able to assign currency a value.

Traceback (most recent call last):
  File "C:/Workspace/harvestFlexitime/main.py", line 8, in <module>
    timeobjects = client.reports_time_clients('20200101', '20201231')
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\harvest\harvest.py", line 836, in reports_time_clients
    return from_dict(data_class=TimeReportResults, data=self._get(url))
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 60, in from_dict
    value = _build_value(type_=field.type, data=transformed_value, config=config)
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 85, in _build_value
    return _build_value_for_collection(collection=type_, data=data, config=config)
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 128, in _build_value_for_collection
    return data.__class__(_build_value(type_=extract_generic(collection)[0], data=item, config=config) for item in data)
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 128, in <genexpr>
    return data.__class__(_build_value(type_=extract_generic(collection)[0], data=item, config=config) for item in data)
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 87, in _build_value
    return from_dict(data_class=type_, data=data, config=config)
  File "C:\Workspace\harvestFlexitime\venv\lib\site-packages\dacite\core.py", line 65, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field.type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "results.currency" - should be "str" instead of value "None" of type "NoneType"

**Comment by bradbase** [comment]
@jonathansaetre Thanks for raising this issue.

**Comment by bradbase** [comment]
Fixed in version 1.5.0

**Comment by jonathansaetre** [comment]
Nice!
