### ISSUE TITLE
exception raises when calling time_entries()

### ISSUE THREAD

**Issue by swiftech** [bradbase/python-harvest_apiv2#3]
call time_entries() function but got exception:

```
dacite.exceptions.WrongTypeError: wrong value type for field "time_entries.cost_rate" - should be "float" instead of value "None" of type "NoneType"
```

**Comment by bradbase** [comment]
@swiftech Are you able to include any context on how you were able to trigger the error?

TimeEntry.cost_rate is currently optional so I would expect it to accommodate a None as well as a float.

**Comment by swiftech** [comment]
Here is the code which I encounter the problem:
```python
        access_token = request.session.get('access_token')
        refresh_token = request.session.get('refresh_token')
        expires_in = request.session.get('expires_in')
        expires_at = request.session.get('expires_at')
        account_id = request.session.get('account_id')
        authorization_code_flow_token = OAuth2_ServerSide_Token(
            access_token=access_token,
            refresh_token=refresh_token,
            expires_in=expires_in,
            expires_at=expires_at)
        authorization_code_flow = OAuth2_ServerSide(
            client_id=CLIENT_ID,
            client_secret=CLIENT_SECRET,
            token=authorization_code_flow_token,
            refresh_url=REFRESH_URL)
        client = harvest.Harvest(URL_PREFIX, authorization_code_flow)
        client.headers['Harvest-Account-Id'] = account_id
        try:
            time_entries = client.time_entries()
        except HarvestError as err:
            print(err)
```

**Comment by swiftech** [comment]
please forget about it, I just used the old v2_dev branch from the python-harvest

**Comment by bradbase** [comment]
If there's a bug, there's a bug.

I find it unusual that the old one works and this one doesn't as they are the same for this feature.

I'm not going to maintain the old v2_dev branch of python-harvest, so it's best to fix this one.

**Comment by swiftech** [comment]
Maybe my bad description made you misunderstanding, I encountered the problem using v2_dev but posted issue here which was wrong, after I turned to this python-harvest_apiv2, `time_entries()` works without exception now. sorry about that.

But, there is one thing maybe you could take a look, If `time_entries()` get empty data from Harvest, the TimeEntries has no `time_entries` property, which means I have to check if the property is exist before accessing data.

**Comment by bradbase** [comment]
Hi @swiftech,

I must have read it incorrectly. My apologies.

It's great to hear there's no bug (for that) :D

As for the empty time_entries, I suspect this is the behavior you have found... Currently the time_entries field has a field(init=False) specification.

```python
@dataclass
class TimeEntries(BasePage):
    time_entries: List[TimeEntry] = field(init=False)
```

Maybe that's a mistake.

If you're able to raise a PR with a fix and a test for time_entries I'll do my best to put it through as quickly as possible.

You're welcome to have a go at any of the others. I may take me a number of weeks to make the time to get to the other collection objects. I think the fix might be easy enough. Writing the tests is going to take a lot of time.

**Comment by swiftech** [comment]
I'd like to, but I'm a newbie in Python, let me learn how it works first, and try to fix it later

**Comment by bradbase** [comment]
No worries.

I think this project is great for learning because it's not overly complicated.

The keys to the solution are likely to be found here; https://docs.python.org/3/library/dataclasses.html

If you would like a hand I'm happy to help.

**Comment by bradbase** [comment]
In the mean time I expect you should be able to use the "total_entries" field of the returned object. If there are no entries this is expected to be zero.

**Comment by bradbase** [comment]
I've tried to write a quick test for the symptom I think you are finding by removing the time_entries field from the returned page.

The Harvest API help says "Each entry in the array is a separate time entry object. If no more time entries are available, the resulting array will be empty.", but if they aren't returning a time_entries field they are in error. That said, I am finding I can't instantiate a TimeEntries object without having a time_entries field.

```python
    def test_time_entries_missing(self):

        time_entries_dict = {
                "per_page":100,
                "total_pages":1,
                "total_entries":0,
                "next_page":None,
                "previous_page":None,
                "page":1,
                "links":{
                        "first":"https://api.harvestapp.com/v2/time_entries?page=1&per_page=100",
                        "next":None,
                        "previous":None,
                        "last":"https://api.harvestapp.com/v2/time_entries?page=1&per_page=100"
                    }
            }

        # time_entries
        httpretty.register_uri(httpretty.GET,
                "https://api.harvestapp.com/api/v2/time_entries?page=1&per_page=100",
                body=json.dumps(time_entries_dict),
                status=200
            )
        time_entries = from_dict(data_class=TimeEntries, data=time_entries_dict)
        requested_time_entries = self.harvest.time_entries()
        self.assertEqual(requested_time_entries, time_entries)

        httpretty.reset()
```

```
Traceback (most recent call last):
  File "C:\Users\bradb\Documents\Python\python-harvest_apiv2\tests\test_timesheets.py", line 709, in test_time_entries_missing
    self.assertEqual(requested_time_entries, time_entries)
  File "c:\users\bradb\appdata\local\programs\python\python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\users\bradb\appdata\local\programs\python\python37\lib\unittest\case.py", line 842, in _baseAssertEqual
    if not first == second:
  File "<string>", line 4, in __eq__
AttributeError: 'TimeEntries' object has no attribute 'time_entries'
```

So I need to find a way to replicate your situation...

**Comment by swiftech** [comment]
I can't replicate it either, it's strange. I will report and try to find out why if encounter again.
